//Raven
pc1078=new Character('Raven', ' PC')
pc1078.addRoll('Flametongue Longsword+str+pro 15 gp 3 lb. Versatile (1d10)', ' 1d20+0', ' slashing ', ' 1d8+0')
pc1078.addRoll('Crossbow, hand+dex+pro 75 gp 3 lb. Ammunition (range 30/120), light, loading', ' 1d20+0', ' piercing ', ' 1d6+0')
pc1078.putAt('1094px', ' 393px' )
pc1078.setClass('Fighter, Battle Master')
pc1078.setLvl('7')
pc1078.setRace('Human')
pc1078.setBackground('Folk Hero, Farmer')
pc1078.setAbility('abi+1 and abi+1')
pc1078.setAC(19)
pc1078.setFortitude(0)
pc1078.setReflex(0)
pc1078.setWill(0)
pc1078.setAcrobatics('')
pc1078.setAlignment('Chaotic Good')
pc1078.setAnimal('exp')
pc1078.setArmor('Chain Shirt AC13+dex max 2')
pc1078.setArcana('')
pc1078.setAthletics('')
pc1078.setBackF('Defining Event, Rustic Hospitality')
pc1078.setBackL('')
pc1078.setBackS('Calligraphers supplies + 3, Carpenters tools + 3, Vehicles (land) + 3')
pc1078.setBackT('Artisan Tools 1 from Alchemist, Brewer, Calligrapher, Carpenter, Cartographer, Cobbler, Cook, Glassblower, Jeweler, Leatherworker, Mason, Painter, Potter, Smith, Tinker, Weaver, or Woodcarver, Land Vehicles')
pc1078.setBonds('')
pc1078.setCha(13)
pc1078.setChaPro('')
pc1078.setCon(16)
pc1078.setConPro('pro')
pc1078.setCurHp(60)
pc1078.setDeception('')
pc1078.setDex(12)
pc1078.setDexPro('')
pc1078.setEquipment('+ 1 chain shirt, + 1 shield Flame tongue longsword, shortsword, dagger, light crossbow Scroll of protection (plants) ')
pc1078.setExperience('')
pc1078.setFeats('')
pc1078.setActionNotes('2 attacks, Fighting Style (Defense), Maneuvers (Maneuver save DC 1 4; Superiority dice 5; Commander s Strike, Menacing Attack, Parry, Rally, Sweeping Attack) ')
pc1078.setFeatureNotes('')
pc1078.setFigure('Miniatures/Fighter.png')
pc1078.setFlaws('')
pc1078.setHistory('')
pc1078.setHitDice('7d10+21')
pc1078.setIdeals('')
pc1078.setInit(19)
pc1078.setImmunity('')
pc1078.setInitBonus('+1')
pc1078.setInsight('exp')
pc1078.setInt(13)
pc1078.setIntimidation('')
pc1078.setIntPro('')
pc1078.setInvestigation('')
pc1078.setLanguages('Common, and 1 language')
pc1078.setMaxHp(67)
pc1078.setCurHp(60)
pc1078.setMedicine('')
pc1078.setNature('')
pc1078.setPerception('exp')
pc1078.setPerformance('')
pc1078.setPersuasion('')
pc1078.setPro('+3')
pc1078.setProficiencies('all armor, shields, simplewpns, martialwpns')
pc1078.setProficienciesRace('1 more skill, 1 more feat')
pc1078.setReligion('')
pc1078.setResistance('')
pc1078.setSaving('str+pro, con+pro')
pc1078.setSenses('')
pc1078.setShield('Shield AC+2')
pc1078.setSize('Medium 5x5ft')
pc1078.setSleight('')
pc1078.setSkills('Animal Handling + 5, Insight + 5, Perception + 5, Survival + 5')
pc1078.setSpeed('30ft')
pc1078.setSpellAbility('')
pc1078.setSpellAbilityNumber('+0')
pc1078.setStealth('')
pc1078.setStr(16)
pc1078.setStrPro('pro')
pc1078.setSurvival('exp')
pc1078.setTrait('15-80 yrs old(65yrs old), 4ft 8in tall+2d10(5ft 3in tall, 110lbs+2d4(115lbs)')
pc1078.setVulnerability('')
pc1078.setWis(14)
pc1078.setWisPro('')
pc1078.setDamageConditions('grappled')
pc1078.setCurSlot1(0)
pc1078.setCurSlot2(0)
pc1078.setCurSlot3(0)
pc1078.setCurSlot4(0)
pc1078.setCurSlot5(0)
pc1078.setCurSlot6(0)
pc1078.setCurSlot7(0)
pc1078.setCurSlot8(0)
pc1078.setCurSlot9(0)
add(pc1078)
//end of Raven
//Kime Master of High Mysteries
pc305=new Character('Kime Master of High Mysteries', ' PC')
pc305.addRoll('Acid Splash,lvl0,1act,instant,60ft,DC8+int+pro vsDEX You hurl a bubble of acid. Choose one or two creatures you can see within range. If you choose two, they must be within 5 feet of each other. A target must succeed on a Dexterity saving throw or take 1d6 acid damage. This spell s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).', ' 1d20+0', ' Acid', ' 1d6+0')
pc305.addRoll('Fire Bolt,lvl0,1act,instant,rng 120ft You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn t being worn or carried. This spell s damage increases by 1d10 when you reach 5th level (2d10), 11th level (3d10), and 17th level (4d10).', ' 1d20+0', ' Fire', ' 1d10+0')
pc305.addRoll('Mage Hand,lvl0,1act,1min,30ft,area A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration or until you dismiss it as an action. The hand vanishes if it is ever more than 30 feet away from you or if you cast this spell again. You can use your action to control the hand. You can use the hand to manipulate an object, open an unlocked door or container, stow or retrieve an item from an open container, or pour the contents out of a vial. You can move the hand up to 30 feet each time you use it. The hand can t attack, activate magic items, or carry more than 10 pounds.', ' 1d20+0', ' Utility', ' 1d8+0')
pc305.addRoll('Mending,lvl0,1min,instant,touch,area This spell repairs a single break or tear in an object you touch, such as a broken chain link, two halves of a broken key, a torn cloak, or a leaking wineskin. As long as the break or tear is no larger than 1 foot in any dimension, you mend it, leaving no trace of the former damage. This spell can physically repair a magic item or construct, but the spell can t restore magic to such an object.', ' 1d20+0', ' Utility', ' 1d8+0')
pc305.addRoll('Ray of Frost,lvl0,1act,instant,60ft,area A frigid beam of blue-white light streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, it takes 1d8 cold damage, and its speed is reduced by 10 feet until the start of your next turn. The spell s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).', ' 1d20+0', ' Cold', ' 1d8+0')
pc305.addRoll('Alarm,lvl1,1min,8hrs,30ft,area You set an alarm against unwanted intrusion. Choose a door, a window, or an area within rng that is no larger than a 20-foot cube. Until the spell ends, an alarm alerts you whenever a Tiny or larger creature touches or enters the warded area. When you cast the spell, you can designate creatures that won t set off the alarm. You also choose whether the alarm is mental or audible. A mental alarm alerts you with a ping in your mind if you are within 1 mile of the warded area. This ping awakens you if you are sleeping. An audible alarm produces the sound of a hand bell for 10 seconds within 60 feet.', ' 1d20+0', ' Detection', ' 0d0+0')
pc305.addRoll('Color Spray,lvl1,1act,1rnd,self,cone 15ftA dazzling array of flashing, colored light springs from your hand. Roll 6d10; the total is how many hit points of creatures this spell can affect. Creatures in a 15-foot cone originating from you are affected in ascending order of their current hit points (ignoring unconscious creatures and creatures that can t see). Starting with the creature that has the lowest current hit points, each creature affected by this spell is blinded until the end of your next turn. Subtract each creature s hit points from the total before moving on to the creature with the next lowest hit points. A creature s hit points must be equal to or less than the remaining total for that creature to be affected. At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, roll an additional 2d10 for each slot level above 1st.', ' 1d20+0', ' Blinded', ' 1d8+0')
pc305.addRoll('Floating Disk,lvl1,1act,1hr,range 30ft This spell creates a circular, horizontal plane of force, 3 feet in diameter and 1 inch thick, that floats 3 feet above the ground in an unoccupied space of your choice that you can see within range. The disk remains for the duration, and can hold up to 500 pounds. If more weight is placed on it, the spell ends, and everything on the disk falls to the ground. The disk is immobile while you are within 20 feet of it. If you move more than 20 feet away from it, the disk follows you so that it remains within 20 feet of you. It can move across uneven terrain, up or down stairs, slopes and the like, but it can t cross an elevation change of 10 feet or more. For example, the disk can t move across a 10-foot-deep pit, nor could it leave such a pit if it was created at the bottom. If you move more than 100 feet from the disk (typically because it can t move around an obstacle to follow you), the spell ends.', ' 1d20+0', ' Movement', ' 1d8+0')
pc305.addRoll('Mage Armor,lvl1,1act,8hrs,touch,area You touch a willing creature who isn t wearing armor, and a protective magical force surrounds it until the spell ends. The target s base AC becomes 13 + its Dexterity modifier. The spell ends if the target dons armor or if you dismiss the spell as an action.', ' 0d0+0', ' Buff', ' 0d0+0')
pc305.addRoll('Sleep,lvl1,1act,1min,rng 90ft sphere 20ftThis spell sends creatures into a magical slumber. Roll 5d8; the total is how many hit points of creatures this spell can affect. Creatures within 20 feet of a point you choose within rng are affected in ascending order of their current hit points (ignoring unconscious creatures). Starting with the creature that has the lowest current hit points, each creature affected by this spell falls unconscious until the spell ends, the sleeper takes damage, or someone uses an action to shake or slap the sleeper awake. Subtract each creature s hit points from the total before moving on to the creature with the next lowest hit points. A creature s hit points must be equal to or less than the remaining total for that creature to be affected. Undead and creatures immune to being charmed aren t affected by this spell. At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, roll an additional 2d8 for each slot level above 1st.', ' 1d20+0', ' Unconscious', ' 1d8+0')
pc305.addRoll('Enlarge/Reduce lvl2,1act,1min,30ft,DC8+int+pro vsCON You cause a creature or an object you can see within rng to grow larger or smaller for the duration. Choose either a creature or an object that is neither worn nor carried. If the target is unwilling, it can make a Constitution saving throw. On a success, the spell has no effect. If the target is a creature, everything it is wearing and carrying changes size with it. Any item dropped by an affected creature returns to normal size at once. Enlarge. The target s size doubles in all dimensions, and its weight is multiplied by eight. This growth increases its size by one category-- from Medium to Large, for example. If there isn t enough room for the target to double its size, the creature or object attains the maximum possible size in the space available. Until the spell ends, the target also has advantage on Strength checks and Strength saving throws. The target s weapons also grow to match its new size. While these weapons are enlarged, the target s attacks with them deal 1d4 extra damage. Reduce. The target s size is halved in all dimensions, and its weight is reduced to one-eighth of normal. This reduction decreases its size by one category--from Medium to Small, for example. Until the spell ends, the target also has disadvantage on Strength checks and Strength saving throws. The target s weapons also shrink to match its new size. While these weapons are reduced, the target s attacks with them deal 1d4 less damage (this can t reduce the damage below 1).', ' 1d20+0', ' Buff Heal', ' 1d8+0')
pc305.addRoll('Ray of Enfeeblement lvl2,1act,1min,60ft,DC8+int+pro vsCON A black beam of enervating energy springs from your finger toward a creature within range. Make a ranged spell attack against the target. On a hit, the target deals only half damage with weapon attacks that use Strength until the spell ends. At the end of each of the target s turns, it can make a Constitution saving throw against the spell. On a success, the spell ends.', ' 1d20+0', ' DeBuff Heal', ' 1d8+0')
pc305.addRoll('Scorching Ray lvl2,1act,instant,rng 120ft You create three rays of fire and hurl them at targets within range. You can hurl them at one target or several. Make a ranged spell attack for each ray. On a hit, the target takes 2d6 fire damage. At Higher Levels. When you cast this spell using a spell slot of 3rd level or higher, you create one additional ray for each slot level above 2nd.', ' 1d20+0', ' Fire', ' 2d6+0')
pc305.addRoll('Fireball,lvl3,1act,instant,rng 150ft sphere 20ftDC8+int+pro vsDEX A bright streak flashes from your pointing finger to a point you choose within rng and then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere centered on that point must make a Dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much damage on a successful one. The fire spreads around corners. It ignites flammable objects in the area that aren t being worn or carried. At Higher Levels. When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.', ' 1d20+0', ' Fire', ' 8d6+0')
pc305.addRoll('Stinking Cloud,lvl3,1act,1min,rng 90ft sphere 20ftDC8+int+pro vsCON You create a 20-foot-radius sphere of yellow, nauseating gas centered on a point within range. The cloud spreads around corners, and its area is heavily obscured. The cloud lingers in the air for the duration. Each creature that is completely within the cloud at the start of its turn must make a Constitution saving throw against poison. On a failed save, the creature spends its action that turn retching and reeling. Creatures that don t need to breathe or are immune to poison automatically succeed on this saving throw. A moderate wind (at least 10 miles per hour) disperses the cloud after 4 rounds. A strong wind (at least 20 miles per hour) disperses it after 1 round.', ' 1d20+0', ' Control', ' 1d8+0')
pc305.addRoll('Ice Storm,lvl4,1act,instant,rng 300ft cylinder 20ftDC8+int+pro vsDEX A hail of rock-hard ice pounds to the ground in a 20-foot-radius, 40-foot-high cylinder centered on a point within range. Each creature in the cylinder must make a Dexterity saving throw. A creature takes 2d8 bludgeoning damage and 4d6 cold damage on a failed save, or half as much damage on a successful one. Hailstones turn the storm s area of effect into difficult terrain until the end of your next turn. At Higher Levels. When you cast this spell using a spell slot of 5th level or higher, the bludgeoning damage increases by 1d8 for each slot level above 4th.', ' 1d20+0', ' Bludgeoning', ' 2d8+0')
pc305.addRoll('Arcane Eye,lvl4,1act,1hr,range 30ft You create an invisible, magical eye within rng that hovers in the air for the duration. You mentally receive visual information from the eye, which has normal vision and darkvision out to 30 feet. The eye can look in every direction. As an action, you can move the eye up to 30 feet in any direction. There is no limit to how far away from you the eye can move, but it can t enter another plane of existence. A solid barrier blocks the eye s movement, but the eye can pass through an opening as small as 1 inch in diameter.', ' 1d20+0', ' Detection', ' 1d8+0')
pc305.addRoll('Telekinesis,lvl5,1act,10min,60ft,area You gain the ability to move or manipulate creatures or objects by thought. When you cast the spell, and as your action each round for the duration, you can exert your will on one creature or object that you can see within range, causing the appropriate effect below. You can affect the same target round after round, or choose a new one at any time. If you switch targets, the prior target is no longer affected by the spell. Creature. You can try to move a Huge or smaller creature. Make an ability check with your spellcasting ability contested by the creature s Strength check. If you win the contest, you move the creature up to 30 feet in any direction, including upward but not beyond the rng of this spell. Until the end of your next turn, the creature is restrained in your telekinetic grip. A creature lifted upward is suspended in mid-air. On subsequent rounds, you can use your action to attempt to maintain your telekinetic grip on the creature by repeating the contest. Object. You can try to move an object that weighs up to 1,000 pounds. If the object isn t being worn or carried, you automatically move it up to 30 feet in any direction, but not beyond the rng of this spell. If the object is worn or carried by a creature, you must make an ability check with your spellcasting ability contested by that creature s Strength check. If you succeed, you pull the object away from that creature and can move it up to 30 feet in any direction but not beyond the rng of this spell. You can exert fine control on objects with your telekinetic grip, such as manipulating a simple tool, opening a door or a container, stowing or retrieving an item from an open container, or pouring the contents from a vial.', ' 1d20+0', ' Control', ' 1d8+0')
pc305.addRoll('Teleportation Circle,lvl5,1min,duration 1 Round rng 10ft As you cast the spell, you draw a 10-foot-diameter circle on the ground inscribed with sigils that link your location to a permanent teleportation circle of your choice whose sigil sequence you know and that is on the same plane of existence as you. A shimmering portal opens within the circle you drew and remains open until the end of your next turn. Any creature that enters the portal instantly appears within 5 feet of the destination circle or in the nearest unoccupied space if that space is occupied. Many major temples, guilds, and other important places have permanent teleportation circles inscribed somewhere within their confines. Each such circle includes a unique sigil sequence--a string of magical runes arranged in a particular pattern. When you first gain the ability to cast this spell, you learn the sigil sequences for two destinations on the Material Plane, determined by the GM. You can learn additional sigil sequences during your adventures. You can commit a new sigil sequence to memory after studying it for 1 minute. You can create a permanent teleportation circle by casting this spell in the same location every day for one year. You need not use the circle to teleport when you cast the spell in this way.', ' 1d20+0', ' teleportation', ' 1d8+0')
pc305.addRoll('Sunbeam,lvl6,1act,1min,self, (60ft) area line 60ftDC8+int+pro vsCON A beam of brilliant light flashes out from your hand in a 5-foot-wide, 60-foot-long line. Each creature in the line must make a Constitution saving throw. On a failed save, a creature takes 6d8 radiant damage and is blinded until your next turn. On a successful save, it takes half as much damage and isn t blinded by this spell. Undead and oozes have disadvantage on this saving throw. You can create a new line of radiance as your action on any turn until the spell ends. For the duration, a mote of brilliant radiance shines in your hand. It sheds bright light in a 30-foot radius and dim light for an additional 30 feet. This light is sunlight.', ' 1d20+0', ' Radiant', ' 6d8+0')
pc305.addRoll('Lightning Bolt,lvl3,1act,each target in 100ft-line 5ft-w DC8+int+pro vsDEX for half dmg', ' 1d20+0', ' Lightning,ignites flammable,+1d6 dmg per higher slot', ' 8d6+0')
pc305.addRoll('Black Tentacles,lvl4,1act,1min,90ft,20x20ft,DC8+int+pro vsDEX or str to free', ' 1d20+0', ' bludgeoning each restrained turn,difficult terrain', ' 3d6+0')
pc305.putAt('1208px', ' 259px' )
pc305.setClass('Wizard, Evoker')
pc305.setLvl('11')
pc305.setRace('Human')
pc305.setBackground('Sage, Scribe')
pc305.setAbility('abi+1 and abi+1')
pc305.setAC(15)
pc305.setFortitude(0)
pc305.setReflex(0)
pc305.setWill(0)
pc305.setAcrobatics('')
pc305.setAlignment('Neutral')
pc305.setAnimal('')
pc305.setArmor('Mage Armor AC13+dex')
pc305.setArcana('exp')
pc305.setAthletics('')
pc305.setBackF('Specialty, Researcher')
pc305.setBackL('2 languages')
pc305.setBackS('Arcana +8, History +8, In- vestigation +8, Medicine +6')
pc305.setBackT('')
pc305.setBonds('')
pc305.setCha(14)
pc305.setChaPro('')
pc305.setCon(16)
pc305.setConPro('')
pc305.setCurHp(79)
pc305.setDeception('')
pc305.setDex(15)
pc305.setDexPro('')
pc305.setEquipment('quarterstaff or dagger component pouch or arcane focus scholar pack or explorer pack spellbook')
pc305.setExperience('')
pc305.setFeats('')
pc305.setActionNotes('')
pc305.setFeatureNotes('')
pc305.setFigure('Miniatures/Wizard.png')
pc305.setFlaws('')
pc305.setHistory('exp')
pc305.setHitDice('0d6+0')
pc305.setIdeals('')
pc305.setInit(21)
pc305.setImmunity('')
pc305.setInitBonus('+2')
pc305.setInsight('')
pc305.setInt(18)
pc305.setIntimidation('')
pc305.setIntPro('pro')
pc305.setInvestigation('exp')
pc305.setLanguages('Common, and 1 language')
pc305.setMaxHp(79)
pc305.setCurHp(79)
pc305.setMedicine('pro')
pc305.setNature('')
pc305.setPerception('')
pc305.setPerformance('')
pc305.setPersuasion('')
pc305.setPro('+4')
pc305.setProficiencies('daggers, darts, light crossbows, quarterstaffs, and slings')
pc305.setProficienciesRace('1 more skill, 1 more feat')
pc305.setReligion('')
pc305.setResistance('')
pc305.setSaving('int+pro, wis+pro')
pc305.setSenses('')
pc305.setShield('No Shield AC+0')
pc305.setSize('Medium 5x5ft')
pc305.setSleight('')
pc305.setSkills('2 from Arcana, History, Insight, Investigation, Medicine, or Religion')
pc305.setSpeed('30ft')
pc305.setSpellAbility('int')
pc305.setSpellAbilityNumber('+4')
pc305.setStealth('')
pc305.setStr(10)
pc305.setStrPro('')
pc305.setSurvival('')
pc305.setTrait('15-80 yrs old(21yrs old), 4ft 8in tall+2d10(6ft 0in tall, 110lbs+2d4(115lbs), Male')
pc305.setVulnerability('')
pc305.setWis(14)
pc305.setWisPro('pro')
pc305.setDamageConditions('')
pc305.setCurSlot1(4)
pc305.setCurSlot2(3)
pc305.setCurSlot3(2)
pc305.setCurSlot4(3)
pc305.setCurSlot5(2)
pc305.setCurSlot6(0)
pc305.setCurSlot7(0)
pc305.setCurSlot8(0)
pc305.setCurSlot9(0)
add(pc305)
//end of Kime Master of High Mysteries
//Lindarfin Lightbreeze
pc9906=new Character('Lindarfin Lightbreeze', ' PC')
pc9906.addRoll(' Mace+str+pro', ' 1d20+0', ' bludgeoning+Spiritual Weapon dmg', ' 1d6+0')
pc9906.addRoll('Shortbow+dex+pro 25 gp 2 lb. Ammunition (range 80/320), two-handed', ' 1d20+0', ' piercing ', ' 1d6+0')
pc9906.addRoll('Guidance,lvl0,1act,1min,touch,area You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends.', ' 1d20+0', ' Buff Heal', ' 1d8+0')
pc9906.addRoll('Spare the Dying,lvl0,1act,instant,touch,area You touch a living creature that has 0 hit points. The creature becomes stable. This spell has no effect on undead or constructs.', ' 1d20+0', ' Healing', ' 1d8+0')
pc9906.addRoll('Thaumaturgy,lvl0,1act,1min,30ft,area You manifest a minor wonder, a sign of supernatural power, within range. You create one of the following magical effects within range: Your voice booms up to three times as loud as normal for 1 minute. You cause flames to flicker, brighten, dim, or change color for 1 minute. You cause harmless tremors in the ground for 1 minute. You create an instantaneous sound that originates from a point of your choice within range, such as a rumble of thunder, the cry of a raven, or ominous whispers. You instantaneously cause an unlocked door or window to fly open or slam shut. You alter the appearance of your eyes for 1 minute. If you cast this spell multiple times, you can have up to three of its 1-minute effects active at a time, and you can dismiss such an effect as an action.', ' 1d20+0', ' Control', ' 1d8+0')
pc9906.addRoll('Mending,lvl0,1min,instant,touch,area This spell repairs a single break or tear in an object you touch, such as a broken chain link, two halves of a broken key, a torn cloak, or a leaking wineskin. As long as the break or tear is no larger than 1 foot in any dimension, you mend it, leaving no trace of the former damage. This spell can physically repair a magic item or construct, but the spell can t restore magic to such an object.', ' 1d20+0', ' Utility', ' 1d8+0')
pc9906.addRoll('Cure Wounds,lvl1,1act,instant,touch,area A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs. At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d8 for each slot level above 1st.', ' 1d20+0', ' Healing', ' 1d8+0')
pc9906.addRoll('Inflict Wounds,lvl1,1act,instant,touch,area Make a melee spell attack against a creature you can reach. On a hit, the target takes 3d10 necrotic damage. At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d10 for each slot level above 1st.', ' 1d20+0', ' Necrotic', ' 1d8+0')
pc9906.addRoll('Sanctuary,lvl1 ,1bonusAct ,1min,30ft,DC8+wis+pro vsWIS You ward a creature within rng against attack. Until the spell ends, any creature who targets the warded creature with an attack or a harmful spell must first make a Wisdom saving throw. On a failed save, the creature must choose a new target or lose the attack or spell. This spell doesn t protect the warded creature from area effects, such as the explosion of a fireball. If the warded creature makes an attack, casts a spell that affects an enemy, or deals damage to another creature, this spell ends.', ' 1d20+0', ' Buff Heal', ' 1d8+0')
pc9906.addRoll('Find Traps lvl2,1act,instant,rng 120ft You sense the presence of any trap within rng that is within line of sight. A trap, for the purpose of this spell, includes anything that would inflict a sudden or unexpected effect you consider harmful or undesirable, which was specifically intended as such by its creator. Thus, the spell would sense an area affected by the alarm spell, a glyph of warding, or a mechanical pit trap, but it would not reveal a natural weakness in the floor, an unstable ceiling, or a hidden sinkhole. This spell merely reveals that a trap is present. You don t learn the location of each trap, but you do learn the general nature of the danger posed by a trap you sense.', ' 1d20+0', ' Detection', ' 1d8+0')
pc9906.addRoll('Gentle Repose lvl2,1act,10days,touch,area You touch a corpse or other remains. For the duration, the target is protected from decay and can t become undead. The spell also effectively extends the time limit on raising the target from the dead, since days spent under the influence of this spell don t count against the time limit of spells such as raise dead.', ' 1d20+0', ' Warding', ' 1d8+0')
pc9906.addRoll('Lesser Restoration lvl2,1act,instant,touch,end 1 disease or condition blinded, deafened, paralyzed, poisoned.', ' 0d0+0', ' Healing', ' 0d0+0')
pc9906.addRoll('Prayer of Healing lvl2,10min,instant,30ft,area Up to six creatures of your choice that you can see within rng each regain hit points equal to 2d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs. At Higher Levels. When you cast this spell using a spell slot of 3rd level or higher, the healing increases by 1d8 for each slot level above 2nd.', ' 1d20+0', ' Healing', ' 1d8+0')
pc9906.addRoll('Bestow Curse,lvl3,1act,1min,touch,DC8+wis+pro vsWIS You touch a creature, and that creature must succeed on a Wisdom saving throw or become cursed for the duration of the spell. When you cast this spell, choose the nature of the curse from the following options: Choose one ability score. While cursed, the target has disadvantage on ability checks and saving throws made with that ability score. While cursed, the target has disadvantage on attack rolls against you. While cursed, the target must make a Wisdom saving throw at the start of each of its turns. If it fails, it wastes its action that turn doing nothing. While the target is cursed, your attacks and spells deal an extra 1d8 necrotic damage to the target. A remove curse spell ends this effect. At the DM s option, you may choose an alternative curse effect, but it should be no more powerful than those described above. The DM has final say on such a curse s effect. At Higher Levels. If you cast this spell using a spell slot of 4th level or higher, the duration is concentration, up to 10 minutes. If you use a spell slot of 5th level or higher, the duration is 8 hours. If you use a spell slot of 7th level or higher, the duration is 24 hours. If you use a 9th level spell slot, the spell lasts until it is dispelled. Using a spell slot of 5th level or higher grants a duration that doesn t require concentration.', ' 1d20+0', ' DeBuff Heal', ' 1d8+0')
pc9906.addRoll('remove Curse,lvl3,1act,instant,touch,area At your touch, all curses affecting one creature or object end. If the object is a cursed magic item, its curse remains, but the spell breaks its owner s attunement to the object so it can be removed or discarded.', ' 1d20+0', ' Buff Heal', ' 1d8+0')
pc9906.addRoll('revivify,lvl3,1act,instant,touch,area You touch a creature that has died within the last minute. That creature returns to life with 1 hit point. This spell can t return to life a creature that has died of old age, nor can it restore any missing body parts.', ' 1d20+0', ' Healing', ' 1d8+0')
pc9906.addRoll('Banishment,lvl4,1act,1min,60ft,DC8+wis+pro vsCHA You attempt to send one creature that you can see within rng to another plane of existence. The target must succeed on a Charisma saving throw or be banished. If the target is native to the plane of existence you re on, you banish the target to a harmless demiplane. While there, the target is incapacitated. The target remains there until the spell ends, at which point the target reappears in the space it left or in the nearest unoccupied space if that space is occupied. If the target is native to a different plane of existence than the one you re on, the target is banished with a faint popping noise, returning to its home plane. If the spell ends before 1 minute has passed, the target reappears in the space it left or in the nearest unoccupied space if that space is occupied. Otherwise, the target doesn t return. At Higher Levels. When you cast this spell using a spell slot of 5th level or higher, you can target one additional creature for each slot level above 4th.', ' 1d20+0', ' Banishment', ' 1d8+0')
pc9906.addRoll('Bless,lvl1,1act,1min,30ft,area You bless up to three creatures of your choice within range. Whenever a target makes an attack roll or a saving throw before the spell ends, the target can roll a d4 and add the number rolled to the attack roll or saving throw. At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.', ' 1d20+0', ' Buff Heal', ' 1d8+0')
pc9906.addRoll('Cure Wounds,lvl1,1act,instant,touch,area A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs. At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d8 for each slot level above 1st.', ' 1d20+0', ' Healing', ' 1d8+0')
pc9906.addRoll('Lesser Restoration lvl2,1act,instant,touch,end 1 disease or condition blinded, deafened, paralyzed, poisoned.', ' 0d0+0', ' Healing', ' 0d0+0')
pc9906.addRoll('Beacon of Hope,lvl3,1act,1min,30ft,area This spell bestows hope and vitality. Choose any number of creatures within range. For the duration, each target has advantage on Wisdom saving throws and death saving throws, and regains the maximum number of hit points possible from any healing.', ' 1d20+0', ' Buff Heal', ' 1d8+0')
pc9906.addRoll('revivify,lvl3,1act,instant,touch,area You touch a creature that has died within the last minute. That creature returns to life with 1 hit point. This spell can t return to life a creature that has died of old age, nor can it restore any missing body parts.', ' 1d20+0', ' Healing', ' 1d8+0')
pc9906.addRoll('Spiritual Weapon,lvl2,1bonusAct,1min,20ft-radius levitate wpn to repeat attack', ' 0d0+0', ' wpn dmg+Force+spellcasting+1d8 every 2nd higher slot', ' 1d8+3')
pc9906.putAt('1207px', ' 399px' )
pc9906.setClass('Cleric, Life')
pc9906.setLvl('6')
pc9906.setRace('Elf, Wood')
pc9906.setBackground('Folk Hero, Farmer')
pc9906.setAbility('dex+2, int+1')
pc9906.setAC(14)
pc9906.setFortitude(0)
pc9906.setReflex(0)
pc9906.setWill(0)
pc9906.setAcrobatics('')
pc9906.setAlignment('Lawful Good')
pc9906.setAnimal('pro')
pc9906.setArmor('No Armor AC10+dex')
pc9906.setArcana('')
pc9906.setAthletics('')
pc9906.setBackF('Defining Event, Rustic Hospitality')
pc9906.setBackL('')
pc9906.setBackS('Animal Handling, Survival')
pc9906.setBackT('Artisan Tools 1 from Alchemist, Brewer, Calligrapher, Carpenter, Cartographer, Cobbler, Cook, Glassblower, Jeweler, Leatherworker, Mason, Painter, Potter, Smith, Tinker, Weaver, or Woodcarver, Land Vehicles')
pc9906.setBonds('')
pc9906.setCha(10)
pc9906.setChaPro('pro')
pc9906.setCon(17)
pc9906.setConPro('')
pc9906.setCurHp(33)
pc9906.setDeception('')
pc9906.setDex(12)
pc9906.setDexPro('')
pc9906.setEquipment('Chain shirt Quarterstaff, mace, short- bow Rope of entanglement, potion of superior healing ')
pc9906.setExperience('')
pc9906.setFeats('')
pc9906.setActionNotes('1st Slots 2/2')
pc9906.setFeatureNotes('(Mask of the Wild)try to hide even under light cover')
pc9906.setFigure('Miniatures/Cleric.png')
pc9906.setFlaws('')
pc9906.setHistory('pro')
pc9906.setHitDice('6d8+18')
pc9906.setIdeals('')
pc9906.setInit(11)
pc9906.setImmunity('Sleep')
pc9906.setInitBonus('+1')
pc9906.setInsight('')
pc9906.setInt(11)
pc9906.setIntimidation('')
pc9906.setIntPro('')
pc9906.setInvestigation('')
pc9906.setLanguages('Common, Elvish')
pc9906.setMaxHp(51)
pc9906.setCurHp(33)
pc9906.setMedicine('pro')
pc9906.setNature('')
pc9906.setPerception('pro')
pc9906.setPerformance('')
pc9906.setPersuasion('')
pc9906.setPro('+3')
pc9906.setProficiencies('light armor, medium armor, shields, simplewpns')
pc9906.setProficienciesRace('Longbows, longswords, shortbows, and shortswords')
pc9906.setReligion('')
pc9906.setResistance('necrotic dmg, (Fae Ancestry)save vs charm@Adv')
pc9906.setSaving('wis+pro, cha+pro')
pc9906.setSenses('Darkvision 60ft, (Keen Senses)Perception+pro, (Trance)alert to danger during long and short rests')
pc9906.setShield('No Shield AC+0')
pc9906.setSize('Medium 5x5ft')
pc9906.setSleight('')
pc9906.setSkills('2 from History, Insight, Medicine, Persuasion, or Religion')
pc9906.setSpeed('35ft')
pc9906.setSpellAbility('wis')
pc9906.setSpellAbilityNumber('+3')
pc9906.setStealth('')
pc9906.setStr(14)
pc9906.setStrPro('')
pc9906.setSurvival('pro')
pc9906.setTrait('100-750 yrs old(325yrs old), 4ft 6in tall+2d10(5ft 2in tall, 100lbs+1d4(101lbs), male')
pc9906.setVulnerability('')
pc9906.setWis(17)
pc9906.setWisPro('pro')
pc9906.setDamageConditions('grappled')
pc9906.setCurSlot1(4)
pc9906.setCurSlot2(3)
pc9906.setCurSlot3(3)
pc9906.setCurSlot4(0)
pc9906.setCurSlot5(0)
pc9906.setCurSlot6(0)
pc9906.setCurSlot7(0)
pc9906.setCurSlot8(0)
pc9906.setCurSlot9(0)
add(pc9906)
//end of Lindarfin Lightbreeze
//Wilhelmina Waywocket
pc5301=new Character('Wilhelmina Waywocket', ' PC')
pc5301.addRoll('Dagger+dex+pro 2 gp 1 lb. Finesse, light, thrown (range 20/60)', ' 1d20+2', ' piercing', ' 1d4+2')
pc5301.addRoll(' Sneak Attack extra damage', ' 0d0+0', ' extra damage', ' 5d6+0')
pc5301.putAt('1311px', ' 145px' )
pc5301.setClass('Rogue, Thief')
pc5301.setLvl('9')
pc5301.setRace('Halfling, Lightfoot')
pc5301.setBackground('Urchin')
pc5301.setAbility('dex+2, cha+1')
pc5301.setAC(16)
pc5301.setFortitude(0)
pc5301.setReflex(0)
pc5301.setWill(0)
pc5301.setAcrobatics('')
pc5301.setAlignment('Chaotic Neutral')
pc5301.setAnimal('')
pc5301.setArmor('No Armor AC10+dex')
pc5301.setArcana('')
pc5301.setAthletics('')
pc5301.setBackF('City Secrets')
pc5301.setBackL('')
pc5301.setBackS('Sleight of Hand, Stealth')
pc5301.setBackT('Disguise Kit, Thieves Tools')
pc5301.setBonds('')
pc5301.setCha(14)
pc5301.setChaPro('pro')
pc5301.setCon(16)
pc5301.setConPro('pro')
pc5301.setCurHp(75)
pc5301.setDeception('')
pc5301.setDex(18)
pc5301.setDexPro('')
pc5301.setEquipment('rapier or shortsword shortbow 20 arrows or shortsword burglar pack or dungeoneer pack or explorer pack leather armor 2 daggers thieves tools')
pc5301.setExperience('')
pc5301.setFeats('')
pc5301.setActionNotes('')
pc5301.setFeatureNotes('')
pc5301.setFigure('Miniatures/Rogue.png')
pc5301.setFlaws('')
pc5301.setHistory('')
pc5301.setHitDice('9d8+27')
pc5301.setIdeals('')
pc5301.setInit(9)
pc5301.setImmunity('')
pc5301.setInitBonus('+4')
pc5301.setInsight('')
pc5301.setInt(15)
pc5301.setIntimidation('')
pc5301.setIntPro('')
pc5301.setInvestigation('')
pc5301.setLanguages('Common, Halfling')
pc5301.setMaxHp(75)
pc5301.setCurHp(75)
pc5301.setMedicine('')
pc5301.setNature('')
pc5301.setPerception('')
pc5301.setPerformance('')
pc5301.setPersuasion('')
pc5301.setPro('+4')
pc5301.setProficiencies('daggers, darts, light crossbows, quarterstaffs, and slings')
pc5301.setProficienciesRace('')
pc5301.setReligion('')
pc5301.setResistance('(Brave)save vs fear@Adv')
pc5301.setSaving('con+pro, cha+pro')
pc5301.setSenses('')
pc5301.setShield('No Shield AC+0')
pc5301.setSize('Small 5x5ft')
pc5301.setSleight('')
pc5301.setSkills('Acrobatics +8, Athletics +5, Investigation* + 1 0, Percep- tion* + 7, Sleight of Hand +8, Stealth* + 1 2, Disguise kit +4, Thieves tools* + 8 (* denotes Expertise) ')
pc5301.setSpeed('25ft')
pc5301.setSpellAbility('int')
pc5301.setSpellAbilityNumber('+2')
pc5301.setStealth('')
pc5301.setStr(12)
pc5301.setStrPro('')
pc5301.setSurvival('')
pc5301.setTrait('(Naturally Stealthy)can try to hide behind larger being, (Nimbleness)can move through larger being space, (Lucky)re-roll on a natural 1, 1-250 years old, 40 lbs., 3fttall, female')
pc5301.setVulnerability('')
pc5301.setWis(8)
pc5301.setWisPro('')
pc5301.setDamageConditions('')
pc5301.setCurSlot1(0)
pc5301.setCurSlot2(0)
pc5301.setCurSlot3(0)
pc5301.setCurSlot4(0)
pc5301.setCurSlot5(0)
pc5301.setCurSlot6(0)
pc5301.setCurSlot7(0)
pc5301.setCurSlot8(0)
pc5301.setCurSlot9(0)
add(pc5301)
//end of Wilhelmina Waywocket
//Curate 1
pc1116=new Character('Curate 1', ' PC')
pc1116.addRoll(' mace', ' 1d20+0', ' ', ' 1d6+1')
pc1116.putAt('640px', ' 139px' )
pc1116.setClass('')
pc1116.setLvl('4')
pc1116.setRace('')
pc1116.setBackground('')
pc1116.setAbility('')
pc1116.setAC(4)
pc1116.setFortitude(0)
pc1116.setReflex(0)
pc1116.setWill(0)
pc1116.setAcrobatics('')
pc1116.setAlignment('Chaotic Neutral')
pc1116.setAnimal('')
pc1116.setArmor('Chain Mail AC16 Stealth @DisAdv str13')
pc1116.setArcana('')
pc1116.setAthletics('')
pc1116.setBackF('')
pc1116.setBackL('')
pc1116.setBackS('')
pc1116.setBackT('')
pc1116.setBonds('')
pc1116.setCha(0)
pc1116.setChaPro('')
pc1116.setCon(0)
pc1116.setConPro('')
pc1116.setCurHp(30)
pc1116.setDeception('')
pc1116.setDex(0)
pc1116.setDexPro('')
pc1116.setEquipment('')
pc1116.setExperience('')
pc1116.setFeats('')
pc1116.setActionNotes('')
pc1116.setFeatureNotes('')
pc1116.setFigure('Miniatures/Monster.png')
pc1116.setFlaws('')
pc1116.setHistory('')
pc1116.setHitDice('')
pc1116.setIdeals('')
pc1116.setImmunity('')
pc1116.setInitBonus('+0')
pc1116.setInsight('')
pc1116.setInt(0)
pc1116.setIntimidation('')
pc1116.setIntPro('')
pc1116.setInvestigation('')
pc1116.setLanguages('')
pc1116.setMaxHp(30)
pc1116.setCurHp(30)
pc1116.setMedicine('')
pc1116.setNature('')
pc1116.setPerception('')
pc1116.setPerformance('')
pc1116.setPersuasion('')
pc1116.setPro('+2')
pc1116.setProficiencies('')
pc1116.setProficienciesRace('')
pc1116.setReligion('')
pc1116.setResistance('')
pc1116.setSaving('')
pc1116.setSenses('')
pc1116.setShield('Shield AC+2')
pc1116.setSize('')
pc1116.setSleight('')
pc1116.setSkills('')
pc1116.setSpeed('')
pc1116.setSpellAbility('')
pc1116.setSpellAbilityNumber('+0')
pc1116.setStealth('')
pc1116.setStr(0)
pc1116.setStrPro('')
pc1116.setSurvival('')
pc1116.setTrait('')
pc1116.setVulnerability('')
pc1116.setWis(0)
pc1116.setWisPro('')
pc1116.setDamageConditions('')
pc1116.setCurSlot1(0)
pc1116.setCurSlot2(0)
pc1116.setCurSlot3(0)
pc1116.setCurSlot4(0)
pc1116.setCurSlot5(0)
pc1116.setCurSlot6(0)
pc1116.setCurSlot7(0)
pc1116.setCurSlot8(0)
pc1116.setCurSlot9(0)
add(pc1116)
//end of Curate 1
